[package]
name = "validate-cpf-cnpj-wasm"
version = "0.1.0"
authors = ["Lílian Ferreira de Freitas<lily.mosquitoes@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
